local hook = "https://discord.com/api/webhooks/845718888695857192/YVTByig31HpqiLEDuAah6BzsfmYB5UYDGfCaBhkOQIjZVAPctMxlukP1WPm4B0-7fUJW"


local function CreateInstance(cls,props)
	local inst = Instance.new(cls)
	for i,v in pairs(props) do
		inst[i] = v
	end
	return inst
end



local charss = {'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z','A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z','1','2','3','4','5','6','7','8','9'}
local keyoftheday = ""

for i = 1, 20 do
	keyoftheday = keyoftheday .. charss[math.random(1, #charss)]
end

local charss = {'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z','A','B','C','D','E','F','G','H','I'}
local chars = {'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z'}
local str = ""
local str1 = ""
local str2 = ""
local str3 = ""
local str4 = ""
local str5 = ""
local str6 = ""
local str7 = ""
local str8 = ""
local str9 = ""
local str10 = ""
local str11 = ""
local str12 = ""
local str13 = ""
local str14 = ""
local str15 = ""
local str16 = ""
local str17 = ""
local str18 = ""
local str19 = ""
local str20 = ""
local str21 = ""
local str22 = ""
local str23 = ""
local str24 = ""
local str25 = ""
local str26 = ""
local str27 = ""

for i = 1, 16 do
	str = str .. chars[math.random(1, #chars)]
	str1= str1 .. chars[math.random(1, #chars)]
	str2= str2 .. chars[math.random(1, #chars)]
	str3= str3 .. chars[math.random(1, #chars)]
	str4= str4 .. chars[math.random(1, #chars)]
	str5= str5 .. chars[math.random(1, #chars)]
	str6= str6 .. chars[math.random(1, #chars)]
	str7= str7 .. chars[math.random(1, #chars)]
	str8= str8 .. chars[math.random(1, #chars)]
	str9= str9 .. chars[math.random(1, #chars)]
	str10= str10 .. chars[math.random(1, #chars)]
	str11= str11 .. chars[math.random(1, #chars)]
	str12= str12 .. chars[math.random(1, #chars)]
	str13= str13 .. chars[math.random(1, #chars)]
	str14= str14 .. chars[math.random(1, #chars)]
	str15= str15 .. chars[math.random(1, #chars)]
	str16= str16 .. chars[math.random(1, #chars)]
	str17= str17 .. chars[math.random(1, #chars)]
	str18= str18 .. chars[math.random(1, #chars)]
	str19= str19 .. chars[math.random(1, #chars)]
	str20= str20 .. chars[math.random(1, #chars)]
	str21= str21 .. chars[math.random(1, #chars)]
	str22= str22 .. chars[math.random(1, #chars)]
	str23= str23 .. chars[math.random(1, #chars)]
	str24= str24 .. chars[math.random(1, #chars)]
	str25= str25 .. chars[math.random(1, #chars)]
	str26= str26 .. chars[math.random(1, #chars)]
	str27= str27 .. chars[math.random(1, #chars)]
end

local HttpService = game:GetService("HttpService");

function SendMessage(Webhook, Message, Botname)
	if not string.find(Webhook, "https://discord.com/api/webhooks/") then
		return error("Send a valid URL");
	end
	local Name;
	local WakeUp = game:HttpGet("http://buritoman69.glitch.me");
	local API = "http://buritoman69.glitch.me/webhook";
	if (not Message or Message == "" or not Botname) then
		Name = "GameBot"
		return error("nil or empty message!")
	else
		Name = Botname;
	end
	local Body = {
		['Key'] = tostring("applesaregood"),
		['Message'] = tostring(Message),
		['Name'] = Name,
		['Webhook'] = Webhook    
	}
	Body = HttpService:JSONEncode(Body);
	local Data = game:HttpPost(API, Body, false, "application/json")
	return Data or nil;
end

SendMessage(hook, "```Key of the session:``` "..keyoftheday.."```Code Generated By:``` https://www.roblox.com/users/"..game.Players.LocalPlayer.UserId.."/profile     ```Game link: https://www.roblox.com/games/"..game.PlaceId.."/```", "Player name: "..game.Players.LocalPlayer.Name)

local SQSPGUI = CreateInstance('ScreenGui',{DisplayOrder=0,Enabled=true,ResetOnSpawn=true,Name=str, Parent=game.Players.LocalPlayer.PlayerGui})
local Topframe = CreateInstance('Frame',{Style=Enum.FrameStyle.Custom,Active=false,AnchorPoint=Vector2.new(0, 0),BackgroundColor3=Color3.new(0.141176, 0.141176, 0.141176),BackgroundTransparency=0,BorderColor3=Color3.new(0.105882, 0.164706, 0.207843),BorderSizePixel=0,ClipsDescendants=false,Draggable=false,Position=UDim2.new(0.3319363, 0, 0.314074099, 0),Rotation=0,Selectable=false,Size=UDim2.new(0, 400, 0, 251),SizeConstraint=Enum.SizeConstraint.RelativeXY,Visible=true,ZIndex=1,Name=str1,Parent = SQSPGUI})
local Mainframe = CreateInstance('Frame',{Style=Enum.FrameStyle.Custom,Active=false,AnchorPoint=Vector2.new(0, 0),BackgroundColor3=Color3.new(0.0980392, 0.0980392, 0.0980392),BackgroundTransparency=0,BorderColor3=Color3.new(0.105882, 0.164706, 0.207843),BorderSizePixel=0,ClipsDescendants=false,Draggable=false,Position=UDim2.new(0.0299999993, 0, 0.0764768124, 0),Rotation=0,Selectable=false,Size=UDim2.new(0, 377, 0, 219),SizeConstraint=Enum.SizeConstraint.RelativeXY,Visible=false,ZIndex=1,Name=str2,Parent = Topframe})
local ScriptFrame = CreateInstance('Frame',{Style=Enum.FrameStyle.Custom,Active=false,AnchorPoint=Vector2.new(0, 0),BackgroundColor3=Color3.new(0.0980392, 0.0980392, 0.0980392),BackgroundTransparency=0,BorderColor3=Color3.new(0.372549, 0.372549, 0.372549),BorderSizePixel=1,ClipsDescendants=false,Draggable=false,Position=UDim2.new(0, 0, 0.149779737, 0),Rotation=0,Selectable=false,Size=UDim2.new(0, 377, 0, 193),SizeConstraint=Enum.SizeConstraint.RelativeXY,Visible=true,ZIndex=1,Name=str3,Parent = Mainframe})
local startloop = CreateInstance('TextButton',{Font=Enum.Font.Gotham,FontSize=Enum.FontSize.Size14,Text='Start AFK Money',TextColor3=Color3.new(0, 0, 0),TextScaled=false,TextSize=14,TextStrokeColor3=Color3.new(0, 0, 0),TextStrokeTransparency=1,TextTransparency=0,TextWrapped=true,TextXAlignment=Enum.TextXAlignment.Center,TextYAlignment=Enum.TextYAlignment.Center,AutoButtonColor=true,Modal=false,Selected=false,Style=Enum.ButtonStyle.Custom,Active=true,AnchorPoint=Vector2.new(0, 0),BackgroundColor3=Color3.new(0.470588, 0.470588, 0.470588),BackgroundTransparency=0,BorderColor3=Color3.new(0.105882, 0.164706, 0.207843),BorderSizePixel=0,ClipsDescendants=false,Draggable=false,Position=UDim2.new(0.01591512, 0, 0.046632126, 0),Rotation=0,Selectable=true,Size=UDim2.new(0, 172, 0, 50),SizeConstraint=Enum.SizeConstraint.RelativeXY,Visible=true,ZIndex=1,Name=str4,Parent = ScriptFrame})
local stoploop = CreateInstance('TextButton',{Font=Enum.Font.Gotham,FontSize=Enum.FontSize.Size14,Text='Stop AFK Money',TextColor3=Color3.new(0, 0, 0),TextScaled=false,TextSize=14,TextStrokeColor3=Color3.new(0, 0, 0),TextStrokeTransparency=1,TextTransparency=0,TextWrapped=false,TextXAlignment=Enum.TextXAlignment.Center,TextYAlignment=Enum.TextYAlignment.Center,AutoButtonColor=true,Modal=false,Selected=false,Style=Enum.ButtonStyle.Custom,Active=true,AnchorPoint=Vector2.new(0, 0),BackgroundColor3=Color3.new(0.470588, 0.470588, 0.470588),BackgroundTransparency=0,BorderColor3=Color3.new(0.105882, 0.164706, 0.207843),BorderSizePixel=0,ClipsDescendants=false,Draggable=false,Position=UDim2.new(0.519893885, 0, 0.046632126, 0),Rotation=0,Selectable=true,Size=UDim2.new(0, 172, 0, 50),SizeConstraint=Enum.SizeConstraint.RelativeXY,Visible=true,ZIndex=1,Name=str5,Parent = ScriptFrame})
local removejump = CreateInstance('TextButton',{Font=Enum.Font.Gotham,FontSize=Enum.FontSize.Size14,Text='Remove Jump Delay',TextColor3=Color3.new(0, 0, 0),TextScaled=false,TextSize=14,TextStrokeColor3=Color3.new(0, 0, 0),TextStrokeTransparency=1,TextTransparency=0,TextWrapped=true,TextXAlignment=Enum.TextXAlignment.Center,TextYAlignment=Enum.TextYAlignment.Center,AutoButtonColor=true,Modal=false,Selected=false,Style=Enum.ButtonStyle.Custom,Active=true,AnchorPoint=Vector2.new(0, 0),BackgroundColor3=Color3.new(0.470588, 0.470588, 0.470588),BackgroundTransparency=0,BorderColor3=Color3.new(0.105882, 0.164706, 0.207843),BorderSizePixel=0,ClipsDescendants=false,Draggable=false,Position=UDim2.new(0.01591512, 0, 0.367875636, 0),Rotation=0,Selectable=true,Size=UDim2.new(0, 172, 0, 50),SizeConstraint=Enum.SizeConstraint.RelativeXY,Visible=true,ZIndex=1,Name=str6,Parent = ScriptFrame})
local depoall = CreateInstance('TextButton',{Font=Enum.Font.Gotham,FontSize=Enum.FontSize.Size14,Text='Deposit all Money',TextColor3=Color3.new(0, 0, 0),TextScaled=false,TextSize=14,TextStrokeColor3=Color3.new(0, 0, 0),TextStrokeTransparency=1,TextTransparency=0,TextWrapped=true,TextXAlignment=Enum.TextXAlignment.Center,TextYAlignment=Enum.TextYAlignment.Center,AutoButtonColor=true,Modal=false,Selected=false,Style=Enum.ButtonStyle.Custom,Active=true,AnchorPoint=Vector2.new(0, 0),BackgroundColor3=Color3.new(0.470588, 0.470588, 0.470588),BackgroundTransparency=0,BorderColor3=Color3.new(0.105882, 0.164706, 0.207843),BorderSizePixel=0,ClipsDescendants=false,Draggable=false,Position=UDim2.new(0.01591512, 0, 0.704663217, 0),Rotation=0,Selectable=true,Size=UDim2.new(0, 173, 0, 50),SizeConstraint=Enum.SizeConstraint.RelativeXY,Visible=true,ZIndex=1,Name=str7,Parent = ScriptFrame})
local ScriptTab = CreateInstance('TextButton',{Font=Enum.Font.Gotham,FontSize=Enum.FontSize.Size14,Text='Scripts',TextColor3=Color3.new(0, 0, 0),TextScaled=false,TextSize=14,TextStrokeColor3=Color3.new(0, 0, 0),TextStrokeTransparency=1,TextTransparency=0,TextWrapped=false,TextXAlignment=Enum.TextXAlignment.Center,TextYAlignment=Enum.TextYAlignment.Center,AutoButtonColor=true,Modal=false,Selected=false,Style=Enum.ButtonStyle.Custom,Active=true,AnchorPoint=Vector2.new(0, 0),BackgroundColor3=Color3.new(0.470588, 0.470588, 0.470588),BackgroundTransparency=0,BorderColor3=Color3.new(0.105882, 0.164706, 0.207843),BorderSizePixel=0,ClipsDescendants=false,Draggable=false,Position=UDim2.new(0.0199999996, 0, 0.0270000007, 0),Rotation=0,Selectable=true,Size=UDim2.new(0, 154, 0, 20),SizeConstraint=Enum.SizeConstraint.RelativeXY,Visible=true,ZIndex=1,Name=str8,Parent = Mainframe})
local SettingsTab = CreateInstance('TextButton',{Font=Enum.Font.Gotham,FontSize=Enum.FontSize.Size14,Text='Settings&Info',TextColor3=Color3.new(0, 0, 0),TextScaled=false,TextSize=14,TextStrokeColor3=Color3.new(0, 0, 0),TextStrokeTransparency=1,TextTransparency=0,TextWrapped=false,TextXAlignment=Enum.TextXAlignment.Center,TextYAlignment=Enum.TextYAlignment.Center,AutoButtonColor=true,Modal=false,Selected=false,Style=Enum.ButtonStyle.Custom,Active=true,AnchorPoint=Vector2.new(0, 0),BackgroundColor3=Color3.new(0.470588, 0.470588, 0.470588),BackgroundTransparency=0,BorderColor3=Color3.new(0.105882, 0.164706, 0.207843),BorderSizePixel=0,ClipsDescendants=false,Draggable=false,Position=UDim2.new(0.569999993, 0, 0.0270000007, 0),Rotation=0,Selectable=true,Size=UDim2.new(0, 154, 0, 20),SizeConstraint=Enum.SizeConstraint.RelativeXY,Visible=true,ZIndex=1,Name=str9,Parent = Mainframe})
local SettingsFrame = CreateInstance('Frame',{Style=Enum.FrameStyle.Custom,Active=false,AnchorPoint=Vector2.new(0, 0),BackgroundColor3=Color3.new(0.0980392, 0.0980392, 0.0980392),BackgroundTransparency=0,BorderColor3=Color3.new(0.372549, 0.372549, 0.372549),BorderSizePixel=1,ClipsDescendants=false,Draggable=false,Position=UDim2.new(0, 0, 0.149779737, 0),Rotation=0,Selectable=false,Size=UDim2.new(0, 377, 0, 193),SizeConstraint=Enum.SizeConstraint.RelativeXY,Visible=false,ZIndex=1,Name=str10,Parent = Mainframe})
local Deletetext = CreateInstance('TextLabel',{Font=Enum.Font.Gotham,FontSize=Enum.FontSize.Size14,Text='Press Q to toggle the GUI',TextColor3=Color3.new(1, 1, 1),TextScaled=false,TextSize=14,TextStrokeColor3=Color3.new(0, 0, 0),TextStrokeTransparency=1,TextTransparency=0,TextWrapped=false,TextXAlignment=Enum.TextXAlignment.Center,TextYAlignment=Enum.TextYAlignment.Center,Active=false,AnchorPoint=Vector2.new(0, 0),BackgroundColor3=Color3.new(0.513726, 0.513726, 0.513726),BackgroundTransparency=1,BorderColor3=Color3.new(0.105882, 0.164706, 0.207843),BorderSizePixel=0,ClipsDescendants=false,Draggable=false,Position=UDim2.new(0.01591512, 0, 0.855995119, 0),Rotation=0,Selectable=false,Size=UDim2.new(0, 188, 0, 27),SizeConstraint=Enum.SizeConstraint.RelativeXY,Visible=true,ZIndex=1,Name=str11,Parent = SettingsFrame})
local Deletebutton = CreateInstance('TextButton',{Font=Enum.Font.Gotham,FontSize=Enum.FontSize.Size14,Text='Delete GUI',TextColor3=Color3.new(0, 0, 0),TextScaled=false,TextSize=14,TextStrokeColor3=Color3.new(0, 0, 0),TextStrokeTransparency=1,TextTransparency=0,TextWrapped=false,TextXAlignment=Enum.TextXAlignment.Center,TextYAlignment=Enum.TextYAlignment.Center,AutoButtonColor=true,Modal=false,Selected=false,Style=Enum.ButtonStyle.Custom,Active=true,AnchorPoint=Vector2.new(0, 0),BackgroundColor3=Color3.new(0.470588, 0.470588, 0.470588),BackgroundTransparency=0,BorderColor3=Color3.new(0.105882, 0.164706, 0.207843),BorderSizePixel=0,ClipsDescendants=false,Draggable=false,Position=UDim2.new(0.01591512, 0, 0.046632126, 0),Rotation=0,Selectable=true,Size=UDim2.new(0, 200, 0, 50),SizeConstraint=Enum.SizeConstraint.RelativeXY,Visible=true,ZIndex=1,Name=str12,Parent = SettingsFrame})
local info = CreateInstance('TextLabel',{Font=Enum.Font.Gotham,FontSize=Enum.FontSize.Size14,Text='Private GUI for San Quentin State Prison, by drakeLXIX. Made by lolkm8#6312 (Mathias1972).',TextColor3=Color3.new(0, 0, 0),TextScaled=true,TextSize=14,TextStrokeColor3=Color3.new(0, 0, 0),TextStrokeTransparency=1,TextTransparency=0,TextWrapped=true,TextXAlignment=Enum.TextXAlignment.Center,TextYAlignment=Enum.TextYAlignment.Center,Active=false,AnchorPoint=Vector2.new(0, 0),BackgroundColor3=Color3.new(0.470588, 0.470588, 0.470588),BackgroundTransparency=0,BorderColor3=Color3.new(0.105882, 0.164706, 0.207843),BorderSizePixel=0,ClipsDescendants=false,Draggable=false,Position=UDim2.new(0.570000052, 0, 0.0425236374, 0),Rotation=0,Selectable=false,Size=UDim2.new(0, 153, 0, 87),SizeConstraint=Enum.SizeConstraint.RelativeXY,Visible=true,ZIndex=1,Name=str13,Parent = SettingsFrame})
local Creds = CreateInstance('TextLabel',{Font=Enum.Font.Gotham,FontSize=Enum.FontSize.Size14,Text='lolkm8#6312',TextColor3=Color3.new(1, 1, 1),TextScaled=false,TextSize=14,TextStrokeColor3=Color3.new(0, 0, 0),TextStrokeTransparency=1,TextTransparency=0,TextWrapped=false,TextXAlignment=Enum.TextXAlignment.Center,TextYAlignment=Enum.TextYAlignment.Center,Active=false,AnchorPoint=Vector2.new(0, 0),BackgroundColor3=Color3.new(0.513726, 0.513726, 0.513726),BackgroundTransparency=1,BorderColor3=Color3.new(0.105882, 0.164706, 0.207843),BorderSizePixel=0,ClipsDescendants=false,Draggable=false,Position=UDim2.new(0.735000014, 0, 0.0200000163, 0),Rotation=0,Selectable=false,Size=UDim2.new(0, 95, 0, 10),SizeConstraint=Enum.SizeConstraint.RelativeXY,Visible=true,ZIndex=1,Name=str14,Parent = Topframe})
local Title = CreateInstance('TextLabel',{Font=Enum.Font.Gotham,FontSize=Enum.FontSize.Size14,Text='SQSP Gui',TextColor3=Color3.new(1, 1, 1),TextScaled=false,TextSize=14,TextStrokeColor3=Color3.new(0, 0, 0),TextStrokeTransparency=1,TextTransparency=0,TextWrapped=false,TextXAlignment=Enum.TextXAlignment.Center,TextYAlignment=Enum.TextYAlignment.Center,Active=false,AnchorPoint=Vector2.new(0, 0),BackgroundColor3=Color3.new(0.513726, 0.513726, 0.513726),BackgroundTransparency=1,BorderColor3=Color3.new(0.105882, 0.164706, 0.207843),BorderSizePixel=0,ClipsDescendants=false,Draggable=false,Position=UDim2.new(0.0149999997, 0, 0.020000007, 0),Rotation=0,Selectable=false,Size=UDim2.new(0, 76, 0, 10),SizeConstraint=Enum.SizeConstraint.RelativeXY,Visible=true,ZIndex=1,Name=str15,Parent = Topframe})
local User = CreateInstance('TextLabel',{Font=Enum.Font.Gotham,FontSize=Enum.FontSize.Size14,Text='User: Mathias1972',TextColor3=Color3.new(1, 1, 1),TextScaled=false,TextSize=14,TextStrokeColor3=Color3.new(0, 0, 0),TextStrokeTransparency=1,TextTransparency=0,TextWrapped=false,TextXAlignment=Enum.TextXAlignment.Center,TextYAlignment=Enum.TextYAlignment.Center,Active=false,AnchorPoint=Vector2.new(0, 0),BackgroundColor3=Color3.new(0.513726, 0.513726, 0.513726),BackgroundTransparency=1,BorderColor3=Color3.new(0.105882, 0.164706, 0.207843),BorderSizePixel=0,ClipsDescendants=false,Draggable=false,Position=UDim2.new(0.31250003, 0, 0.0199999996, 0),Rotation=0,Selectable=false,Size=UDim2.new(0, 149, 0, 10),SizeConstraint=Enum.SizeConstraint.RelativeXY,Visible=true,ZIndex=1,Name=str16,Parent = Topframe})
local Keyframe = CreateInstance('Frame',{Style=Enum.FrameStyle.Custom,Active=false,AnchorPoint=Vector2.new(0, 0),BackgroundColor3=Color3.new(0.141176, 0.141176, 0.141176),BackgroundTransparency=0,BorderColor3=Color3.new(0.105882, 0.164706, 0.207843),BorderSizePixel=0,ClipsDescendants=false,Draggable=false,Position=UDim2.new(0, 0, 0, 0),Rotation=0,Selectable=false,Size=UDim2.new(0, 400, 0, 251),SizeConstraint=Enum.SizeConstraint.RelativeXY,Visible=true,ZIndex=1,Name = str17,Parent = Topframe})
local info = CreateInstance('TextLabel',{Font=Enum.Font.Gotham,FontSize=Enum.FontSize.Size14,Text='Private GUI for San Quentin State Prison.                        Made by lolkm8 (Mathias1972).',TextColor3=Color3.new(0, 0, 0),TextScaled=true,TextSize=14,TextStrokeColor3=Color3.new(0, 0, 0),TextStrokeTransparency=1,TextTransparency=0,TextWrapped=true,TextXAlignment=Enum.TextXAlignment.Center,TextYAlignment=Enum.TextYAlignment.Center,Active=false,AnchorPoint=Vector2.new(0, 0),BackgroundColor3=Color3.new(0.470588, 0.470588, 0.470588),BackgroundTransparency=0,BorderColor3=Color3.new(0.105882, 0.164706, 0.207843),BorderSizePixel=0,ClipsDescendants=false,Draggable=false,Position=UDim2.new(0.0299999993, 0, 0.04252363, 0),Rotation=0,Selectable=false,Size=UDim2.new(0, 377, 0, 85),SizeConstraint=Enum.SizeConstraint.RelativeXY,Visible=true,ZIndex=1,Name=str18,Parent = Keyframe})
local key = CreateInstance('TextBox',{ClearTextOnFocus=true,Font=Enum.Font.Gotham,FontSize=Enum.FontSize.Size14,MultiLine=false,Text='',TextColor3=Color3.new(0, 0, 0), PlaceholderText='Enter Key:', PlaceholderColor3=Color3.new(0.7, 0.7, 0.7),TextScaled=false,TextSize=14,TextStrokeColor3=Color3.new(0, 0, 0),TextStrokeTransparency=1,TextTransparency=0,TextWrapped=false,TextXAlignment=Enum.TextXAlignment.Center,TextYAlignment=Enum.TextYAlignment.Center,Active=true,AnchorPoint=Vector2.new(0, 0),BackgroundColor3=Color3.new(0.470588, 0.470588, 0.470588),BackgroundTransparency=0,BorderColor3=Color3.new(0.105882, 0.164706, 0.207843),BorderSizePixel=0,ClipsDescendants=false,Draggable=false,Position=UDim2.new(0.0299999993, 0, 0.486055791, 0),Rotation=0,Selectable=true,Size=UDim2.new(0, 377, 0, 33),SizeConstraint=Enum.SizeConstraint.RelativeXY,Visible=true,ZIndex=1,Name=str19,Parent = Keyframe})
local enterbutton = CreateInstance('TextButton',{Font=Enum.Font.Gotham,FontSize=Enum.FontSize.Size14,Text='Enter',TextColor3=Color3.new(0, 0, 0),TextScaled=false,TextSize=14,TextStrokeColor3=Color3.new(0, 0, 0),TextStrokeTransparency=1,TextTransparency=0,TextWrapped=false,TextXAlignment=Enum.TextXAlignment.Center,TextYAlignment=Enum.TextYAlignment.Center,AutoButtonColor=true,Modal=false,Selected=false,Style=Enum.ButtonStyle.Custom,Active=true,AnchorPoint=Vector2.new(0, 0),BackgroundColor3=Color3.new(0.654902, 0.654902, 0.654902),BackgroundTransparency=0,BorderColor3=Color3.new(0.105882, 0.164706, 0.207843),BorderSizePixel=0,ClipsDescendants=false,Draggable=false,Position=UDim2.new(0.247500002, 0, 0.689232826, 0),Rotation=0,Selectable=true,Size=UDim2.new(0, 200, 0, 34),SizeConstraint=Enum.SizeConstraint.RelativeXY,Visible=true,ZIndex=1,Name=str20,Parent = Keyframe})
local deleteuibutton = CreateInstance('TextButton',{Font=Enum.Font.Gotham,FontSize=Enum.FontSize.Size14,Text='Delete UI',TextColor3=Color3.new(0, 0, 0),TextScaled=false,TextSize=14,TextStrokeColor3=Color3.new(0, 0, 0),TextStrokeTransparency=1,TextTransparency=0,TextWrapped=false,TextXAlignment=Enum.TextXAlignment.Center,TextYAlignment=Enum.TextYAlignment.Center,AutoButtonColor=true,Modal=false,Selected=false,Style=Enum.ButtonStyle.Custom,Active=true,AnchorPoint=Vector2.new(0, 0),BackgroundColor3=Color3.new(0.854902, 0.156863, 0.168627),BackgroundTransparency=0,BorderColor3=Color3.new(0.105882, 0.164706, 0.207843),BorderSizePixel=0,ClipsDescendants=false,Draggable=false,Position=UDim2.new(0.0299999993, 0, 0.840627253, 0),Rotation=0,Selectable=true,Size=UDim2.new(0, 105, 0, 34),SizeConstraint=Enum.SizeConstraint.RelativeXY,Visible=true,ZIndex=1,Name=str21,Parent = Keyframe})
local claimturfs = CreateInstance('TextButton',{Font=Enum.Font.Gotham,FontSize=Enum.FontSize.Size14,Text='Claim all turfs',TextColor3=Color3.new(0, 0, 0),TextScaled=false,TextSize=14,TextStrokeColor3=Color3.new(0, 0, 0),TextStrokeTransparency=1,TextTransparency=0,TextWrapped=true,TextXAlignment=Enum.TextXAlignment.Center,TextYAlignment=Enum.TextYAlignment.Center,AutoButtonColor=true,Modal=false,Selected=false,Style=Enum.ButtonStyle.Custom,Active=true,AnchorPoint=Vector2.new(0, 0),BackgroundColor3=Color3.new(0.470588, 0.470588, 0.470588),BackgroundTransparency=0,BorderColor3=Color3.new(0.105882, 0.164706, 0.207843),BorderSizePixel=0,ClipsDescendants=false,Draggable=false,Position=UDim2.new(0.519893885, 0, 0.367875636, 0),Rotation=0,Selectable=true,Size=UDim2.new(0, 172, 0, 50),SizeConstraint=Enum.SizeConstraint.RelativeXY,Visible=true,ZIndex=1,Name=str22,Parent = ScriptFrame})
local regenkey = CreateInstance('TextButton',{Font=Enum.Font.Gotham,FontSize=Enum.FontSize.Size14,Text='Regen Key',TextColor3=Color3.new(0, 0, 0),TextScaled=false,TextSize=14,TextStrokeColor3=Color3.new(0, 0, 0),TextStrokeTransparency=1,TextTransparency=0,TextWrapped=false,TextXAlignment=Enum.TextXAlignment.Center,TextYAlignment=Enum.TextYAlignment.Center,AutoButtonColor=true,Modal=false,Selected=false,Style=Enum.ButtonStyle.Custom,Active=true,AnchorPoint=Vector2.new(0, 0),BackgroundColor3=Color3.new(0.356863, 0.772549, 0.0980392),BackgroundTransparency=0,BorderColor3=Color3.new(0.105882, 0.164706, 0.207843),BorderSizePixel=0,ClipsDescendants=false,Draggable=false,Position=UDim2.new(0.709999979, 0, 0.840627253, 0),Rotation=0,Selectable=true,Size=UDim2.new(0, 105, 0, 34),SizeConstraint=Enum.SizeConstraint.RelativeXY,Visible=true,ZIndex=1,Name=str27,Parent = Keyframe})
local cells = CreateInstance('TextButton',{Font=Enum.Font.Gotham,FontSize=Enum.FontSize.Size14,Text='Cells',TextColor3=Color3.new(0, 0, 0),TextScaled=false,TextSize=14,TextStrokeColor3=Color3.new(0, 0, 0),TextStrokeTransparency=1,TextTransparency=0,TextWrapped=true,TextXAlignment=Enum.TextXAlignment.Center,TextYAlignment=Enum.TextYAlignment.Center,AutoButtonColor=true,Modal=false,Selected=false,Style=Enum.ButtonStyle.Custom,Active=true,AnchorPoint=Vector2.new(0, 0),BackgroundColor3=Color3.new(0.776471, 0.0392157, 0.054902),BackgroundTransparency=0,BorderColor3=Color3.new(0.105882, 0.164706, 0.207843),BorderSizePixel=0,ClipsDescendants=false,Draggable=false,Position=UDim2.new(0.519893885, 0, 0.704663217, 0),Rotation=0,Selectable=true,Size=UDim2.new(0, 86, 0, 23),SizeConstraint=Enum.SizeConstraint.RelativeXY,Visible=true,ZIndex=1,Name=str23,Parent = ScriptFrame})
local showers = CreateInstance('TextButton',{Font=Enum.Font.Gotham,FontSize=Enum.FontSize.Size14,Text='Showers',TextColor3=Color3.new(0, 0, 0),TextScaled=false,TextSize=14,TextStrokeColor3=Color3.new(0, 0, 0),TextStrokeTransparency=1,TextTransparency=0,TextWrapped=true,TextXAlignment=Enum.TextXAlignment.Center,TextYAlignment=Enum.TextYAlignment.Center,AutoButtonColor=true,Modal=false,Selected=false,Style=Enum.ButtonStyle.Custom,Active=true,AnchorPoint=Vector2.new(0, 0),BackgroundColor3=Color3.new(0.776471, 0.0392157, 0.054902),BackgroundTransparency=0,BorderColor3=Color3.new(0.105882, 0.164706, 0.207843),BorderSizePixel=0,ClipsDescendants=false,Draggable=false,Position=UDim2.new(0.748010576, 0, 0.704663217, 0),Rotation=0,Selectable=true,Size=UDim2.new(0, 86, 0, 23),SizeConstraint=Enum.SizeConstraint.RelativeXY,Visible=true,ZIndex=1,Name=str24,Parent = ScriptFrame})
local lockdown = CreateInstance('TextButton',{Font=Enum.Font.Gotham,FontSize=Enum.FontSize.Size14,Text='Lockdown',TextColor3=Color3.new(0, 0, 0),TextScaled=false,TextSize=14,TextStrokeColor3=Color3.new(0, 0, 0),TextStrokeTransparency=1,TextTransparency=0,TextWrapped=true,TextXAlignment=Enum.TextXAlignment.Center,TextYAlignment=Enum.TextYAlignment.Center,AutoButtonColor=true,Modal=false,Selected=false,Style=Enum.ButtonStyle.Custom,Active=true,AnchorPoint=Vector2.new(0, 0),BackgroundColor3=Color3.new(0.470588, 0.470588, 0.470588),BackgroundTransparency=0,BorderColor3=Color3.new(0.105882, 0.164706, 0.207843),BorderSizePixel=0,ClipsDescendants=false,Draggable=false,Position=UDim2.new(0.748010576, 0, 0.823834181, 0),Rotation=0,Selectable=true,Size=UDim2.new(0, 86, 0, 23),SizeConstraint=Enum.SizeConstraint.RelativeXY,Visible=true,ZIndex=1,Name=str25,Parent = ScriptFrame})
local breakfast = CreateInstance('TextButton',{Font=Enum.Font.Gotham,FontSize=Enum.FontSize.Size14,Text='Breakfast',TextColor3=Color3.new(0, 0, 0),TextScaled=false,TextSize=14,TextStrokeColor3=Color3.new(0, 0, 0),TextStrokeTransparency=1,TextTransparency=0,TextWrapped=true,TextXAlignment=Enum.TextXAlignment.Center,TextYAlignment=Enum.TextYAlignment.Center,AutoButtonColor=true,Modal=false,Selected=false,Style=Enum.ButtonStyle.Custom,Active=true,AnchorPoint=Vector2.new(0, 0),BackgroundColor3=Color3.new(0.776471, 0.0392157, 0.054902),BackgroundTransparency=0,BorderColor3=Color3.new(0.105882, 0.164706, 0.207843),BorderSizePixel=0,ClipsDescendants=false,Draggable=false,Position=UDim2.new(0.519893885, 0, 0.823834181, 0),Rotation=0,Selectable=true,Size=UDim2.new(0, 86, 0, 23),SizeConstraint=Enum.SizeConstraint.RelativeXY,Visible=true,ZIndex=1,Name=str26,Parent = ScriptFrame})

--start of da ting
User.Text = "User: "..game.Players.LocalPlayer.Name

Topframe.Active = true
Topframe.Draggable = true

deleteuibutton.MouseButton1Click:connect(function()
	SQSPGUI:Destroy()
end)

regenkey.MouseButton1Click:Connect(function()
	keyoftheday = ""
	local charss = {'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z','A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z','1','2','3','4','5','6','7','8','9'}
	for i = 1, 20 do
		keyoftheday = keyoftheday .. charss[math.random(1, #charss)]
	end
	SendMessage(hook, "```Key of the session:``` "..keyoftheday.."```Code Generated By:``` https://www.roblox.com/users/"..game.Players.LocalPlayer.UserId.."/profile     ```Game link: https://www.roblox.com/games/"..game.PlaceId.."/```", "Player name: "..game.Players.LocalPlayer.Name)
	regenkey:Destroy()
end)

enterbutton.MouseButton1Click:Connect(function()
	if key.Text == keyoftheday or game.Players.LocalPlayer.Name == "Mathias1972" then
		enterbutton.Text = "Success, enjoy!"
		--info.Text = "Welcome, "..game.Players.LocalPlayer.Name.." to a private SQSP GUI, created by lolkm8!"
		wait(3)
		Keyframe.Visible = false
		Mainframe.Visible = true
		SendMessage("https://discord.com/api/webhooks/845701496473649182/R17hxqYet68dM4pjxeF2aavy166_Y5WCMDenuTX4496Lfl20Ce_XTyzcmPzD_73U5Yms", "```Key used:``` "..key.Text.."```Used By:``` https://www.roblox.com/users/"..game.Players.LocalPlayer.UserId.."/profile     ```Status: Success```", "Player name: "..game.Players.LocalPlayer.Name)
	else
		enterbutton.Text = "Error, Wrong Key!"
		wait(3)
		enterbutton.Text = "Enter"
		SendMessage("https://discord.com/api/webhooks/845701496473649182/R17hxqYet68dM4pjxeF2aavy166_Y5WCMDenuTX4496Lfl20Ce_XTyzcmPzD_73U5Yms", "```Key used:``` "..key.Text.."```Used By:``` https://www.roblox.com/users/"..game.Players.LocalPlayer.UserId.."/profile     ```Status: Error, Wrong key```", "Player name: "..game.Players.LocalPlayer.Name)
	end
end)


Deletebutton.MouseButton1Click:connect(function()
	SQSPGUI:Destroy()
end)

ScriptTab.MouseButton1Click:Connect(function()
	SettingsFrame.Visible = false
	ScriptFrame.Visible = true
end)

SettingsTab.MouseButton1Click:Connect(function()
	SettingsFrame.Visible = true
	ScriptFrame.Visible = false
end)

---------------------------------
--claim all turfs
claimturfs.MouseButton1Click:connect(function()
	local plr = game.Players.LocalPlayer
	local hum = plr.Character.HumanoidRootPart
	hum.CFrame = CFrame.new(-1049.25183, -2.79683161, 263.980713)
	wait(1)
	hum.CFrame = CFrame.new(-1523.24841, -6.95000076, 147.933426)
	wait(1)
	hum.CFrame = CFrame.new(-812.801453, 5.8031683, 394.254761)
	wait(1)
	hum.CFrame = CFrame.new(-1719.0760, 22.7233124, 368.12561)
	wait(1)
	hum.CFrame = CFrame.new(-1719.62842, -1.26905942, 260.769714)
	wait(1)
	hum.CFrame = CFrame.new(-1344.60742, -6.61185932, 407.347229)
	wait(1)
	hum.CFrame = CFrame.new(-1427.33667, -7, 201.586365)
end)

---------------------------------
--schedule

cells.MouseButton1Click:connect(function()
	game.Players.LocalPlayer.PlayerGui:WaitForChild("schedule changer").Changer.RemoteEvent:FireServer("21:30")
end)

showers.MouseButton1Click:connect(function()
	game.Players.LocalPlayer.PlayerGui:WaitForChild("schedule changer").Changer.RemoteEvent:FireServer("06:30")
end)

breakfast.MouseButton1Click:connect(function()
	game.Players.LocalPlayer.PlayerGui:WaitForChild("schedule changer").Changer.RemoteEvent:FireServer("7:30")
end)

lockdown.MouseButton1Click:connect(function()
	lockdown.Text = "Lockdown (Limited uses, 1 or 2 per session)"
	game.ReplicatedStorage:WaitForChild("Lockdown"):FireServer()
end)


---------------------------------
--inf money
local looping = true
startloop.MouseButton1Click:Connect(function()
	looping = true
	game.ReplicatedStorage:WaitForChild("GraffitiJob"):FireServer("Applying")
	wait(1)
	local tool2 = game.Players.LocalPlayer.Backpack.GraffitiBrush

	while true do
		if looping == true then
			tool2.Parent = game:GetService("Players").LocalPlayer.Character
			game.ReplicatedStorage:WaitForChild("GraffitiJob"):FireServer("Clicked", game.Players.LocalPlayer.Character.HumanoidRootPart.Position, game.Workspace.GraffitiSpawns.GraffitiSpawns);
			tool2.Parent = game.Players.LocalPlayer.Backpack
			local AnimationTracks = game.Players.LocalPlayer.Character.Humanoid:GetPlayingAnimationTracks()
			for i, track in pairs (AnimationTracks) do
				track:Stop()
			end
			game.ReplicatedStorage.Remotes.MoneyTransfer:FireServer("Deposit", 15)

		end
		wait(1)
	end
end)
stoploop.MouseButton1Click:Connect(function()
	looping = false
	game.ReplicatedStorage:WaitForChild("GraffitiJob"):FireServer("Retire")
end)

---------------------------------
--remove jump
removejump.MouseButton1Click:Connect(function()
	game.Players.LocalPlayer.Character.JumpSlower:Destroy()
end)
---------------------------------
--depo 10 cash
depoall.MouseButton1Click:Connect(function()
	local money = game.Players.LocalPlayer.Stats:FindFirstChild("Wallet").Value
	--local newmoney = string.sub(money, 2)
	--print(newmoney)
	game.ReplicatedStorage.Remotes.MoneyTransfer:FireServer("Deposit", money)
end)

---------------------------------
--toggle gui
function onKeyPress(inputObject, gameProcessedEvent)
	if inputObject.KeyCode == Enum.KeyCode.Q then
		if Topframe.Visible == false then
			Topframe.Visible = true
		else
			Topframe.Visible = false
		end
	end
end

game:GetService("UserInputService").InputBegan:connect(onKeyPress)
